export const LANG_CONFIG: Record<string, { color: string, abbr: string }> = {
    // Common Languages
    'Go': { color: '#00ADD8', abbr: 'GO' },
    'JavaScript': { color: '#F7DF1E', abbr: 'JS' },
    'TypeScript': { color: '#3178C6', abbr: 'TS' },
    'Python': { color: '#3776AB', abbr: 'PY' },
    'Java': { color: '#E34F26', abbr: 'JA' },
    'C++': { color: '#00599C', abbr: 'C+' },
    'C++ Header': { color: '#f34b7d', abbr: 'HPP' },
    'C': { color: '#A8B9CC', abbr: 'C' },
    'C Header': { color: '#555555', abbr: 'H' },
    'C#': { color: '#178600', abbr: 'C#' },
    'Rust': { color: '#DEA584', abbr: 'RS' },
    'HTML': { color: '#E34F26', abbr: 'HT' },
    'CSS': { color: '#1572B6', abbr: 'CS' },
    'JSON': { color: '#FBC02D', abbr: '{}' },
    'Markdown': { color: '#9CA3AF', abbr: 'MD' },
    'YAML': { color: '#CB171E', abbr: 'YL' },
    'SQL': { color: '#CC2927', abbr: 'DB' },
    'Makefile': { color: '#6D6D6D', abbr: 'MK' },
    'Vue': { color: '#4FC08D', abbr: 'VU' },
    'Svelte': { color: '#ff3e00', abbr: 'SV' },
    'JSX': { color: '#61DAFB', abbr: 'JSX' },

    // Shell Languages
    'BASH': { color: '#4EAA25', abbr: 'SH' },
    'Bourne Shell': { color: '#4EAA25', abbr: 'SH' },
    'Zsh': { color: '#89e051', abbr: 'ZSH' },
    'C Shell': { color: '#4EAA25', abbr: 'CSH' },
    'Fish': { color: '#4AAE46', abbr: 'FSH' },
    'Plan9 Shell': { color: '#4EAA25', abbr: 'P9' },
    'PowerShell': { color: '#012456', abbr: 'PS' },

    // Systems & Low Level
    'Assembly': { color: '#6E4C13', abbr: 'ASM' },
    'D': { color: '#ba595e', abbr: 'D' },
    'Zig': { color: '#ec915c', abbr: 'ZIG' },
    'Nim': { color: '#ffc200', abbr: 'NIM' },
    'Odin': { color: '#60AFFE', abbr: 'OD' },
    'Mojo': { color: '#ff4c4c', abbr: 'MJ' },
    'VimL': { color: '#199f4b', abbr: 'VIM' },
    'CUDA': { color: '#76B900', abbr: 'CU' },
    'Verilog': { color: '#b2b7f8', abbr: 'V' },
    'VHDL': { color: '#adb2cb', abbr: 'VHDL' },
    'Hare': { color: '#DB7093', abbr: 'HA' },
    'Carbon': { color: '#0d0000', abbr: 'CAR' },
    'Cairo': { color: '#F39C12', abbr: 'CAI' },

    // Scripting & Dynamic
    'Ruby': { color: '#701516', abbr: 'RB' },
    'Ruby HTML': { color: '#701516', abbr: 'ERB' },
    'PHP': { color: '#4F5D95', abbr: 'PHP' },
    'Perl': { color: '#0298c3', abbr: 'PL' },
    'Lua': { color: '#000080', abbr: 'LUA' },
    'R': { color: '#198CE7', abbr: 'R' },
    'Dart': { color: '#00B4AB', abbr: 'DA' },
    'Elixir': { color: '#6e4a7e', abbr: 'EX' },
    'Erlang': { color: '#B83998', abbr: 'ERL' },
    'Julia': { color: '#a270ba', abbr: 'JL' },
    'Crystal': { color: '#000100', abbr: 'CR' },
    'Groovy': { color: '#e69f56', abbr: 'GR' },
    'Tcl/Tk': { color: '#e4cc98', abbr: 'TCL' },
    'Cython': { color: '#3776AB', abbr: 'CY' },
    'Awk': { color: '#4B6C4B', abbr: 'AWK' },
    'sed': { color: '#64B5F6', abbr: 'SED' },
    'Ring': { color: '#0d47a1', abbr: 'RNG' },

    // Functional Languages
    'Haskell': { color: '#5e5086', abbr: 'HS' },
    'OCaml': { color: '#3be133', abbr: 'ML' },
    'Clojure': { color: '#db5855', abbr: 'CLJ' },
    'F#': { color: '#b845fc', abbr: 'F#' },
    'F*': { color: '#572E91', abbr: 'FST' },
    'Scala': { color: '#DC322F', abbr: 'SC' },
    'LISP': { color: '#3fb68b', abbr: 'LSP' },
    'Scheme': { color: '#1e4aec', abbr: 'SCH' },
    'Racket': { color: '#3c5caa', abbr: 'RKT' },
    'Elm': { color: '#60B5CC', abbr: 'ELM' },
    'Standard ML': { color: '#dc566d', abbr: 'SML' },
    'Reason': { color: '#DD4B39', abbr: 'RE' },
    'Coq': { color: '#D0B68C', abbr: 'COQ' },
    'Lean': { color: '#7B68EE', abbr: 'LEA' },
    'Idris': { color: '#b30000', abbr: 'IDR' },
    'Frege': { color: '#5e5086', abbr: 'FRG' },
    'Dhall': { color: '#3776AB', abbr: 'DHL' },

    // Config & Data
    'TOML': { color: '#9c4221', abbr: 'TML' },
    'XML': { color: '#0060ac', abbr: 'XML' },
    'XML resource': { color: '#0060ac', abbr: 'XRC' },
    'XSD': { color: '#0060ac', abbr: 'XSD' },
    'XSLT': { color: '#EB8CE5', abbr: 'XSL' },
    'Protocol Buffers': { color: '#0085ba', abbr: 'PB' },
    'HCL': { color: '#844FBA', abbr: 'HCL' },
    'Nix': { color: '#7e7eff', abbr: 'NIX' },
    'CMake': { color: '#064f8c', abbr: 'CM' },
    'Meson': { color: '#007800', abbr: 'MES' },
    'Ant': { color: '#A81C7D', abbr: 'ANT' },
    'Maven': { color: '#C71A36', abbr: 'MVN' },
    'MSBuild script': { color: '#512BD4', abbr: 'MSB' },

    // Mobile & Apple
    'Swift': { color: '#F05138', abbr: 'SW' },
    'Objective-C': { color: '#438eff', abbr: 'OBJ' },
    'Objective-C++': { color: '#6866fb', abbr: 'O++' },
    'Kotlin': { color: '#A97BFF', abbr: 'KT' },

    // Web & Frontend
    'LESS': { color: '#1d365d', abbr: 'LSS' },
    'Sass': { color: '#a53b70', abbr: 'SAS' },
    'CoffeeScript': { color: '#244776', abbr: 'COF' },
    'LiveScript': { color: '#499886', abbr: 'LS' },
    'Handlebars': { color: '#f7931e', abbr: 'HBS' },
    'Mustache': { color: '#724B24', abbr: 'MUS' },
    'Nunjucks': { color: '#1C4913', abbr: 'NJK' },
    'JSP': { color: '#007396', abbr: 'JSP' },

    // Blockchain & Smart Contracts
    'Solidity': { color: '#AA6746', abbr: 'SOL' },
    'Vyper': { color: '#3776AB', abbr: 'VYP' },
    'Move': { color: '#4A90D9', abbr: 'MOV' },
    'Circom': { color: '#F39C12', abbr: 'CIR' },
    'Yul': { color: '#AA6746', abbr: 'YUL' },

    // Graphics & Shaders
    'GLSL': { color: '#5686a5', abbr: 'GL' },
    'HLSL': { color: '#5686a5', abbr: 'HL' },

    // Notebook & Documentation
    'Jupyter Notebook': { color: '#DA5B0B', abbr: 'NB' },
    'RMarkdown': { color: '#198CE7', abbr: 'RMD' },
    'ReStructuredText': { color: '#141414', abbr: 'RST' },
    'AsciiDoc': { color: '#E40046', abbr: 'ADC' },
    'TeX': { color: '#3D6117', abbr: 'TEX' },

    // Legacy & Specialized
    'ActionScript': { color: '#882B0F', abbr: 'AS' },
    'Ada': { color: '#02f88c', abbr: 'AD' },
    'Arduino Sketch': { color: '#bd79d1', abbr: 'ARD' },
    'Batch': { color: '#C1F12E', abbr: 'BAT' },
    'COBOL': { color: '#118f9e', abbr: 'COB' },
    'FORTRAN Legacy': { color: '#4d41b1', abbr: 'F77' },
    'FORTRAN Modern': { color: '#4d41b1', abbr: 'F90' },
    'MATLAB': { color: '#e16737', abbr: 'MAT' },
    'Pascal': { color: '#E3F171', abbr: 'PAS' },
    'Prolog': { color: '#74283c', abbr: 'PRL' },
    'Visual Basic': { color: '#945db7', abbr: 'VB' },
    'Plain Text': { color: '#9ca3af', abbr: 'TXT' },

    // Newer & Modern Languages
    'Ballerina': { color: '#FF5000', abbr: 'BAL' },
    'Gleam': { color: '#FFAFF3', abbr: 'GLM' },
    'Hy': { color: '#7891b1', abbr: 'HY' },
    'Janet': { color: '#AA55AA', abbr: 'JNT' },
    'Koka': { color: '#1C4A2A', abbr: 'KOK' },
    'Motoko': { color: '#3B00B9', abbr: 'MO' },
    'Pony': { color: '#374649', abbr: 'PON' },
    'Terra': { color: '#00004C', abbr: 'TRA' },
    'Umka': { color: '#4B6C88', abbr: 'UMK' },
    'Zephir': { color: '#118f9e', abbr: 'ZEP' },

    // DSLs & Query Languages
    'ANTLR': { color: '#E44D26', abbr: 'ANT' },
    'Gherkin': { color: '#5B2063', abbr: 'GHK' },
    'RAML': { color: '#77D9FB', abbr: 'RML' },
    'Rego': { color: '#7D9199', abbr: 'REG' },
    'Q': { color: '#0070CD', abbr: 'Q' },
    'QML': { color: '#41CD52', abbr: 'QML' },
    'PRQL': { color: '#CE552C', abbr: 'PRQ' },
    'Stan': { color: '#B2011D', abbr: 'STN' },
    'TLA': { color: '#7830A5', abbr: 'TLA' },

    // Build & Automation
    'Just': { color: '#384D54', abbr: 'JST' },
    'Starlark': { color: '#76D275', abbr: 'STR' },
    'LD Script': { color: '#6D6D6D', abbr: 'LDS' },
    'Yacc': { color: '#4B6C88', abbr: 'YAC' },
    'lex': { color: '#DBCA00', abbr: 'LEX' },
    'M4': { color: '#6D6D6D', abbr: 'M4' },

    // Less Common Languages
    'Alda': { color: '#FF6F61', abbr: 'ALD' },
    'ATS': { color: '#1AC620', abbr: 'ATS' },
    'AutoHotkey': { color: '#334455', abbr: 'AHK' },
    'Berry': { color: '#15A193', abbr: 'BRY' },
    'Bicep': { color: '#519ABA', abbr: 'BIC' },
    'BitBake': { color: '#FF6600', abbr: 'BB' },
    'Cap\'n Proto': { color: '#A0522D', abbr: 'CPN' },
    'Carp': { color: '#ADD8E6', abbr: 'CRP' },
    'Chapel': { color: '#8DC63F', abbr: 'CHP' },
    'ColdFusion': { color: '#ED2D41', abbr: 'CF' },
    'ColdFusion CFScript': { color: '#ED2D41', abbr: 'CFS' },
    'Device Tree': { color: '#6D6D6D', abbr: 'DTS' },
    'DTrace': { color: '#6D6D6D', abbr: 'DTR' },
    'Eiffel': { color: '#4D6977', abbr: 'EIF' },
    'Expect': { color: '#6D6D6D', abbr: 'EXP' },
    'Factor': { color: '#636746', abbr: 'FCT' },
    'Haxe': { color: '#EA8220', abbr: 'HX' },
    'Imba': { color: '#16CEC6', abbr: 'IMB' },
    'Inno Setup': { color: '#264B99', abbr: 'ISS' },
    'Io': { color: '#a9188d', abbr: 'IO' },
    'Isabelle': { color: '#FEFE00', abbr: 'ISB' },
    'JAI': { color: '#A46F2A', abbr: 'JAI' },
    'KakouneScript': { color: '#6F8F72', abbr: 'KAK' },
    'Lilypond': { color: '#9ACD32', abbr: 'LY' },
    'Logtalk': { color: '#295B9A', abbr: 'LGT' },
    'Mercury': { color: '#FF7F00', abbr: 'MRC' },
    'Nearley': { color: '#990000', abbr: 'NRL' },
    'NSIS': { color: '#3a8dc0', abbr: 'NSI' },
    'Nu': { color: '#c9df40', abbr: 'NU' },
    'Ohm': { color: '#FFB347', abbr: 'OHM' },
    'Polly': { color: '#4169E1', abbr: 'PLY' },
    'Rebol': { color: '#358A5B', abbr: 'REB' },
    'Red': { color: '#f50000', abbr: 'RED' },
    'SKILL': { color: '#339933', abbr: 'SKL' },
    'Unity-Prefab': { color: '#000000', abbr: 'UNI' },
    'Vala': { color: '#7239b7', abbr: 'VAL' },
    'WiX': { color: '#0070C1', abbr: 'WIX' },
};

export const getLanguageColor = (lang: string) => LANG_CONFIG[lang]?.color || '#8b949e';
export const getLanguageAbbr = (lang: string) => LANG_CONFIG[lang]?.abbr || (lang ? lang.slice(0, 2).toUpperCase() : '..');